### ISSUE TITLE
Can equiformer predict force using energy gradients?

### ISSUE THREAD

**Issue by YutackPark** [atomicarchitects/equiformer_v2#14]
I looked into codes and the paper, and it seems like equiformer predict force directly, rather than using gradient of energy. Although there is pros and cons, I'm curious whether is there any plan to making force predictions from energy gradient, which could be implemented using autograd.

**Comment by yilunliao** [comment]
Hi @YutackPark 

I have implemented the gradient method for force prediction in Equiformer(V1) and have examples on MD17:
https://github.com/atomicarchitects/equiformer

For EquiformerV2, the fairchem repo is implementing the gradient method, and you can follow their implementation here: https://github.com/FAIR-Chem/fairchem/tree/eqv2_grad_force_fix_detach
I think they would merge to their main branch soon.
